-- DEPRECATED: Do not run on production.
-- This file previously added wide-open RLS policies for the `anon` role.
-- The app requires Supabase Auth (Google) and the JWT email must exist in public.staff_email_allowlist.
-- See schema.sql and migrations staff_only_rls_policies / staff_email_allowlist.
